main: me.rayzr522.factionsanticreep.FactionsAntiCreep

name: ${project.name}
description: ${project.description}
version: ${project.version}
authors: [Rayzr, Ricky Lafleur]

commands:
  factionsanticreep:
    description: The main command for FactionsAntiCreep.
    # aliases: []